
import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import {api } from "y/utils/api";



const ProfilePage: NextPage = () => {

  //Start Fetching asap
  api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center ">
          <div>Profile View</div>
      </main>
    </>
  );
}

export default ProfilePage;